export const USER_ROLES = {
  CITIZEN: "citizen",
  WORKER: "worker",
  ADMIN: "admin",
};

export const ISSUE_STATUSES = {
  PENDING: "PENDING",
  VERIFIED: "VERIFIED",
  ASSIGNED: "ASSIGNED",
  IN_PROGRESS: "IN_PROGRESS",
  PENDING_VERIFICATION: "PENDING_VERIFICATION",
  RESOLVED: "RESOLVED",
  CLOSED: "CLOSED",
  REJECTED: "REJECTED",
};

export const SEVERITY_LEVELS = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
};

export const ISSUE_CATEGORIES = [
  { id: "pothole", label: "Road Damage & Pothole", department: "Public Works Department (PWD)" },
  { id: "water_leak", label: "Water Leakage / Pipe Burst", department: "Water Supply & Sewage Board" },
  { id: "streetlight", label: "Streetlight Outage", department: "Municipal Electrical Dept" },
  { id: "garbage", label: "Garbage & Waste Overflow", department: "Solid Waste & Sanitation" },
  { id: "traffic_signal", label: "Traffic Signal Failure", department: "Traffic Management Bureau" },
  { id: "drainage", label: "Drainage / Sewage Blockage", department: "Solid Waste & Sanitation" },
  { id: "illegal_dumping", label: "Illegal Debris Dumping", department: "Solid Waste & Sanitation" },
  { id: "other", label: "Other Civic Concern", department: "Public Works Department (PWD)" },
];

export const DEPARTMENTS = [
  { id: "pwd", name: "Public Works Department (PWD)", head: "Er. Rajesh Sharma", activeIssues: 42, resolvedIssues: 380, slaRating: "94%" },
  { id: "water", name: "Water Supply & Sewage Board", head: "Er. Priya Nair", activeIssues: 28, resolvedIssues: 290, slaRating: "91%" },
  { id: "electrical", name: "Municipal Electrical Dept", head: "Er. Amit Verma", activeIssues: 19, resolvedIssues: 410, slaRating: "97%" },
  { id: "sanitation", name: "Solid Waste & Sanitation", head: "Sunita Rao", activeIssues: 35, resolvedIssues: 520, slaRating: "89%" },
  { id: "traffic", name: "Traffic Management Bureau", head: "Inspector K. Rathore", activeIssues: 12, resolvedIssues: 175, slaRating: "96%" },
];

export const INITIAL_ORGANIZATIONS = [
  {
    id: "org_del_pwd_01",
    name: "Delhi PWD Metropolitan Road Infrastructure Division",
    categoryIds: ["pothole", "drainage", "other"],
    categoryLabels: ["Road Damage & Pothole", "Drainage / Sewage Blockage"],
    state: "Delhi",
    city: "New Delhi",
    district: "North Delhi",
    serviceArea: "North & Central Delhi Ring Road Arterials",
    jurisdictionRadiusKm: 30,
    centerCoords: { lat: 28.6139, lng: 77.2090 },
    activeWorkers: 48,
    slaRating: "96%",
    phone: "+91 11 2336 1234",
    email: "pwd.delhi.north@civicvision.gov.in",
    type: "MUNICIPAL",
    headOfOrg: "Er. Rajesh Sharma (Superintending Engineer)"
  },
  {
    id: "org_del_ndmc_02",
    name: "New Delhi Municipal Council (NDMC) Civil Works",
    categoryIds: ["pothole", "streetlight", "garbage"],
    categoryLabels: ["Road Damage & Pothole", "Streetlight Outage", "Garbage Overflow"],
    state: "Delhi",
    city: "New Delhi",
    district: "Central Delhi",
    serviceArea: "Lutyens Delhi & Central Business District",
    jurisdictionRadiusKm: 20,
    centerCoords: { lat: 28.6250, lng: 77.2180 },
    activeWorkers: 35,
    slaRating: "98%",
    phone: "+91 11 2334 5678",
    email: "ndmc.civil@civicvision.gov.in",
    type: "MUNICIPAL",
    headOfOrg: "Er. Amit Saxena (Chief Engineer)"
  },
  {
    id: "org_del_djb_03",
    name: "Delhi Jal Board (DJB) Emergency Pipeline & Sewerage",
    categoryIds: ["water_leak", "drainage"],
    categoryLabels: ["Water Leakage / Pipe Burst", "Drainage / Sewage Blockage"],
    state: "Delhi",
    city: "New Delhi",
    district: "All Delhi Districts",
    serviceArea: "All Delhi NCR Metropolitan Sluice Network",
    jurisdictionRadiusKm: 40,
    centerCoords: { lat: 28.6200, lng: 77.2100 },
    activeWorkers: 42,
    slaRating: "92%",
    phone: "+91 11 2352 9000",
    email: "djb.emergency@civicvision.gov.in",
    type: "STATE_AGENCY",
    headOfOrg: "Er. Priya Nair (Executive Director)"
  },
  {
    id: "org_del_bses_04",
    name: "BSES Yamuna Electrical Grid & Streetlight Corps",
    categoryIds: ["streetlight", "traffic_signal"],
    categoryLabels: ["Streetlight Outage", "Traffic Signal Failure"],
    state: "Delhi",
    city: "East Delhi",
    district: "East & South Delhi",
    serviceArea: "Trans-Yamuna & South Delhi Feeder Pillars",
    jurisdictionRadiusKm: 25,
    centerCoords: { lat: 28.6010, lng: 77.2020 },
    activeWorkers: 29,
    slaRating: "97%",
    phone: "+91 11 3999 9707",
    email: "bses.streetlight@civicvision.gov.in",
    type: "PRIVATE_CONTRACTOR",
    headOfOrg: "Er. Amit Verma (Grid Superintendent)"
  },
  {
    id: "org_del_mcd_05",
    name: "MCD Solid Waste Management & Sanitation Wing",
    categoryIds: ["garbage", "illegal_dumping"],
    categoryLabels: ["Garbage & Waste Overflow", "Illegal Debris Dumping"],
    state: "Delhi",
    city: "New Delhi",
    district: "East Delhi",
    serviceArea: "East & North Delhi Municipal Zones",
    jurisdictionRadiusKm: 35,
    centerCoords: { lat: 28.6090, lng: 77.2270 },
    activeWorkers: 65,
    slaRating: "91%",
    phone: "+91 11 2322 8000",
    email: "mcd.sanitation@civicvision.gov.in",
    type: "MUNICIPAL",
    headOfOrg: "Sunita Rao (Sanitation Director)"
  },
  {
    id: "org_pun_pwd_01",
    name: "Punjab PWD & Infrastructure Development Board (Ludhiana)",
    categoryIds: ["pothole", "drainage", "other"],
    categoryLabels: ["Road Damage & Pothole", "Drainage / Sewage Blockage"],
    state: "Punjab",
    city: "Ludhiana",
    district: "Ludhiana",
    serviceArea: "Ludhiana Metropolitan Urban & GT Road Fringe",
    jurisdictionRadiusKm: 35,
    centerCoords: { lat: 30.9010, lng: 75.8573 },
    activeWorkers: 38,
    slaRating: "93%",
    phone: "+91 161 240 1234",
    email: "pwd.ludhiana@punjab.gov.in",
    type: "STATE_AGENCY",
    headOfOrg: "Er. Gurpreet Singh (Chief Engineer)"
  },
  {
    id: "org_mh_bmc_01",
    name: "Brihanmumbai Municipal Corporation (BMC) Roads & Pavement",
    categoryIds: ["pothole", "drainage", "other"],
    categoryLabels: ["Road Damage & Pothole", "Drainage / Sewage Blockage"],
    state: "Maharashtra",
    city: "Mumbai",
    district: "Mumbai Suburbs",
    serviceArea: "Western & Eastern Express Highways & Suburbs",
    jurisdictionRadiusKm: 40,
    centerCoords: { lat: 19.0760, lng: 72.8777 },
    activeWorkers: 72,
    slaRating: "95%",
    phone: "+91 22 2262 0251",
    email: "bmc.roads@mcgm.gov.in",
    type: "MUNICIPAL",
    headOfOrg: "Er. Sunil Joshi (Chief Engineer Roads)"
  },
  {
    id: "org_ka_bbmp_01",
    name: "Bruhat Bengaluru Mahanagara Palike (BBMP) Infrastructure Division",
    categoryIds: ["pothole", "drainage", "water_leak"],
    categoryLabels: ["Road Damage & Pothole", "Drainage / Sewage", "Water Leakage"],
    state: "Karnataka",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    serviceArea: "ORR, Whitefield, Koramangala & Central Bengaluru",
    jurisdictionRadiusKm: 35,
    centerCoords: { lat: 12.9716, lng: 77.5946 },
    activeWorkers: 60,
    slaRating: "93%",
    phone: "+91 80 2266 0000",
    email: "bbmp.infra@bbmp.gov.in",
    type: "MUNICIPAL",
    headOfOrg: "Er. Ramesh Babu (Chief Engineer)"
  },
  {
    id: "org_up_pwd_01",
    name: "UP PWD & Smart City Lucknow Road Management",
    categoryIds: ["pothole", "drainage", "streetlight"],
    categoryLabels: ["Road Damage & Pothole", "Drainage", "Streetlight Outage"],
    state: "Uttar Pradesh",
    city: "Lucknow",
    district: "Lucknow",
    serviceArea: "Gomti Nagar, Hazratganj & Greater Lucknow",
    jurisdictionRadiusKm: 30,
    centerCoords: { lat: 26.8467, lng: 80.9462 },
    activeWorkers: 44,
    slaRating: "91%",
    phone: "+91 522 223 9000",
    email: "uppwd.lucknow@up.gov.in",
    type: "STATE_AGENCY",
    headOfOrg: "Er. Alok Pandey (Chief Engineer)"
  },
  {
    id: "org_up_noida_02",
    name: "Noida & Greater Noida Development Authority (Civil)",
    categoryIds: ["pothole", "traffic_signal", "streetlight", "garbage"],
    categoryLabels: ["Road Damage", "Traffic Signal", "Streetlight", "Garbage"],
    state: "Uttar Pradesh",
    city: "Noida",
    district: "Gautam Buddha Nagar",
    serviceArea: "Noida Expressway & Sectors 1-150",
    jurisdictionRadiusKm: 25,
    centerCoords: { lat: 28.5355, lng: 77.3910 },
    activeWorkers: 50,
    slaRating: "97%",
    phone: "+91 120 242 5025",
    email: "noida.civil@noidaauthorityonline.com",
    type: "MUNICIPAL",
    headOfOrg: "Er. Rajiv Tyagi (General Manager)"
  },
  {
    id: "org_tn_gcc_01",
    name: "Greater Chennai Corporation (GCC) Bridges & Road Department",
    categoryIds: ["pothole", "drainage", "streetlight"],
    categoryLabels: ["Road Damage & Pothole", "Drainage", "Streetlight Outage"],
    state: "Tamil Nadu",
    city: "Chennai",
    district: "Chennai",
    serviceArea: "North, Central & South Chennai Zones",
    jurisdictionRadiusKm: 35,
    centerCoords: { lat: 13.0827, lng: 80.2707 },
    activeWorkers: 55,
    slaRating: "94%",
    phone: "+91 44 2538 4520",
    email: "gcc.roads@chennaicorporation.gov.in",
    type: "MUNICIPAL",
    headOfOrg: "Er. S. Radhakrishnan (Chief Engineer)"
  }
];

export const PLACEHOLDER_IMAGES = {
  pothole: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=800&auto=format&fit=crop&q=80",
  streetlight: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80",
  garbage: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=800&auto=format&fit=crop&q=80",
  waterLeak: "https://images.unsplash.com/photo-1584467735815-f778f274e296?w=800&auto=format&fit=crop&q=80",
  trafficSignal: "https://images.unsplash.com/photo-1508873535684-277a3cbcc4e8?w=800&auto=format&fit=crop&q=80",
  repairedRoad: "https://images.unsplash.com/photo-1578885136359-16c8bd4d3a8e?w=800&auto=format&fit=crop&q=80",
  defaultIssue: "https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=800&auto=format&fit=crop&q=80"
};

export const MAX_GEOFENCE_METERS = 250;
export const MAX_ORGANIZATION_RADIUS_KM = 75;
